name: Build documentation

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-doc]

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Checkout Interruptor
        uses: actions/checkout@v2
        with:
          repository: frenchyeti/interruptor
          path: interruptor
          
      - name: Cleanup output
        run: 'rm -rf $GITHUB_WORKSPACE/public  && git pull'
        
      - name: Install TypeDoc
        run: 'npm install -g typedoc'
        
      - name: Build
        run: 'cd $GITHUB_WORKSPACE/interruptor && ls -la  && typedoc --name interruptor --out $GITHUB_WORKSPACE/public --entryPointStrategy packages .'
          
      - name: Cleanup interruptor
        run: 'rm -rf $GITHUB_WORKSPACE/interruptor'
        
      - name: Update repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update doc
